### ISSUE TITLE
代码运行进去，第一个水管就是封闭死的，鸟飞过去必死

### ISSUE THREAD

**Issue by xuleijvbw** [ellisonchan/ComposeBird#1]

**Comment by ellisonchan** [comment]
你怎么再现的，我运行过很多次，没这个问题。

**Comment by xuleijvbw** [comment]
找个Android 6.0系统的设备试试，分辨率低一些的手机

**Comment by xuleijvbw** [comment]
想问下怎么改，才可以适配有问题的机型呢。我尝试改了下，改的不太对，还是不行

**Comment by ellisonchan** [comment]
时间匆忙，管道高度的随机范围目前是写死的。屏幕高度不同，管道布局的区域高度确实也应该不同。你可以试着改下子。

可以在管道区域布局就是那个farbackground描画得到高度之后，通知viewmodel将管道的范围和间隔改下子。

比如管道高度的随机范围改为，区域布局高度的20%～60%，上下管道间距改为布局的20%，剩余的那个管道则等于总布局高度-上管道的随机值-间距。

**Comment by xuleijvbw** [comment]
好的，改了一下是可以了。但是会偶现崩溃java.lang.IllegalArgumentException: minWidth(150) and minHeight(-57) must be >= 0。你那边有空可以改一下上传到仓库里吗，看下你那边代码怎么做适配的。

**Comment by ellisonchan** [comment]
你怎么改的，可以把代码pull上来，我看下。

**Comment by ellisonchan** [comment]
另外，我创建了个模拟器，是6.0版本、分辨率很低，是480*854的。

运行一切正常，没有问题。

你那边分辨率具体多少？

**Comment by xuleijvbw** [comment]
1920x1080

**Comment by ellisonchan** [comment]
我提交了。

管道高度按照屏幕高度进行了correct（管道高度是区域高度的20%~60%，间隔则是20%）。
另外防止小鸟在低分辨率设备上显得过大，也correct了（小鸟高度采用管道间隔的30%）。

PS.讲道理小鸟的上升和下降幅度也应该按照屏幕高度调节下，以后再改吧~

你看下有没有问题。

**Comment by xuleijvbw** [comment]
👍我看看
